language: php

sudo: false

matrix:
  include:
    - php: 7.1

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/docheader check --exclude-dir=vendor .
